fieldLayouts:
  bd46d2de-fe1f-4e45-b7be-64ea7293900c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: episodes
hasUrls: true
name: Episodes
settings:
  bucket: nwo
  contentDisposition: ''
  endpoint: 'https://nyc3.digitaloceanspaces.com'
  expires: '3 months'
  keyId: $DO_ACCESS_KEY
  region: nyc3
  secret: $DO_SECRET_KEY
  subfolder: brandjam
sortOrder: 1
type: vaersaagod\dospaces\Volume
url: 'https://nwo.nyc3.cdn.digitaloceanspaces.com'
