contentColumnType: string
fieldGroup: 402036bc-20ab-42f8-bfec-f23921cc2162
handle: audioFile
instructions: ''
name: 'Audio file'
searchable: true
settings:
  allowSelfRelations: ''
  allowedKinds:
    - audio
  defaultUploadLocationSource: 'volume:0e7e0708-4a30-403c-9870-96a460b5668a'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add audio'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:0e7e0708-4a30-403c-9870-96a460b5668a'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: ''
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
