contentColumnType: text
fieldGroup: 402036bc-20ab-42f8-bfec-f23921cc2162
handle: episodeLength
instructions: 'hh:mm:ss format is needed'
name: 'Episode length'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
