contentColumnType: string
fieldGroup: 402036bc-20ab-42f8-bfec-f23921cc2162
handle: episodeResources
instructions: ''
name: 'Episode resources'
searchable: true
settings:
  contentTable: '{{%matrixcontent_episoderesources}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
