contentColumnType: text
fieldGroup: 402036bc-20ab-42f8-bfec-f23921cc2162
handle: episodeDescription
instructions: ''
name: 'Episode Description'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
