contentColumnType: text
fieldGroup: ef71a456-3bfb-4f43-8c5b-3479c15e7092
handle: podcastTitle
instructions: ''
name: 'Podcast title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
