contentColumnType: string
fieldGroup: ef71a456-3bfb-4f43-8c5b-3479c15e7092
handle: podcastEmail
instructions: ''
name: 'Podcast email'
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
