contentColumnType: string
fieldGroup: ef71a456-3bfb-4f43-8c5b-3479c15e7092
handle: podcastImage
instructions: ''
name: 'Podcast image'
searchable: false
settings:
  allowSelfRelations: false
  allowedKinds: null
  defaultUploadLocationSource: 'volume:0e7e0708-4a30-403c-9870-96a460b5668a'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: 'Add an image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:0e7e0708-4a30-403c-9870-96a460b5668a'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
