contentColumnType: string
fieldGroup: da4450d1-bd40-4e0c-babd-0222d53253cc
handle: scottsProfilePic
instructions: ''
name: 'Scotts profile pic'
searchable: false
settings:
  allowSelfRelations: false
  allowedKinds: null
  defaultUploadLocationSource: 'volume:0e7e0708-4a30-403c-9870-96a460b5668a'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:0e7e0708-4a30-403c-9870-96a460b5668a'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
