contentColumnType: text
fieldGroup: da4450d1-bd40-4e0c-babd-0222d53253cc
handle: subheading
instructions: ''
name: Subheading
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
