dateModified: 1598253116
email:
  fromEmail: ryan@newwordorder.com.au
  fromName: 'Brand Jam'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      prependSender: 'On behalf of'
      prependSubject: 'New message from Brand Jam'
      successFlashMessage: 'Your message has been sent.'
      toEmail: ryan@newwordorder.com.au
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 2.1.2
  gathercontent:
    edition: standard
    enabled: true
    schemaVersion: '1'
    settings:
      apiKey: dc8f426c-a9bd-4ed7-9874-aebeb9b2b2ec
      username: ryan@newwordorder.com.au
      volumeHandle: episodes
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.1.1
  simple-sharing:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  wordsmith:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0.0
system:
  edition: solo
  live: true
  name: 'Brand Jam'
  schemaVersion: 3.5.12
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
