dateModified: 1597643805
email:
  fromEmail: ryan@newwordorder.com.au
  fromName: 'Brand Jam'
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
plugins:
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 2.1.2
  gathercontent:
    edition: standard
    enabled: true
    schemaVersion: '1'
    settings:
      apiKey: dc8f426c-a9bd-4ed7-9874-aebeb9b2b2ec
      username: ryan@newwordorder.com.au
      volumeHandle: episodes
  wordsmith:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0.0
system:
  edition: pro
  live: true
  name: 'Brand Jam'
  schemaVersion: 3.5.12
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
