fieldLayouts:
  fc00542c-7ebd-4ded-93a4-42255261cd7f:
    tabs:
      -
        elements:
          -
            fieldUid: ff35bc10-9f73-4ca1-a83f-25a57f13e323
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 74bd2ca9-a7af-4c93-9b6b-d647ac0039f4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: b25353ca-1ee0-4b36-b986-356cc4182de2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: f18ba451-d3fb-4723-86d3-ff6db797e597
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 513611f7-f2c2-49a3-a503-2991d0baf8e9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'RSS Globals'
        sortOrder: 1
handle: rssGlobals
name: 'RSS Globals'
